= Zebra Datawedge/Couchbase Mobile Integration Demo

This application implements a simple inventory scanning capability.

The data consists of information about a fictitious set of books.
Scanning the included ISBN bar codes pulls up the information from the link:https://www.couchbase.com/products/lite[Couchbase Lite] embedded database.
It relies on the link:https://www.zebra.com/us/en/products/software/mobile-computers/datawedge.html[Zebra Datawedge] service for ISBN barcode scanning.

The book covers were created using Canva (https://www.canva.com/).
All book cover images are from Unsplash (https://unsplash.com/), and have generously been may available for use free of charge.
Inclusion in this work does not imply additional rights beyond those granted by the copyright holders.

This overall project, as applicable, is released under terms of the Apache 2.0 License.
See `LICENSE` for details.

== Instructions

Load the included data into Couchbase Server using link:https://developer.couchbase.com/documentation/server/current/cli/restore-cbrestore.html[`cbrestore`].
For example, on a standard Linux installation, use `/opt/couchbase/bin/cbrestore /<absolute path>/data http://localhost:8091 -u Administrator -p Password -x rehash=1`
Note the original export with cbbackup was done under macOS.
Restoring under other operating systems requires the additional `-x rehash=1` option.
See the `cbrestore` documentation for details.

Run Couchbase Sync Gateway with the included configuration file.

Open the android folder in Android Studio, build, and install the app on an appropriate Zebra device.
(This application was originally built and test on a Zebra TC56 device.)
The default database URL refers to localhost, so to test on a tethered device, set up port forwarding with `adb reverse tcp:4984 tcp:4984`.

Scan the included barcodes.
The one named "missing" has no associated book in the original data.
The other three barcodes will bring up different books.